### ISSUE TITLE
Stop completions inside of comments

### ISSUE THREAD

**Issue by nicholas-peterson** [fsharp/emacs-fsharp-mode#102]
### Description

Often I'll be writing a comment using '///','//', or '(* .. *)' and want to enter a carriage return or tab. If company mode suggests a completion right as I'm doing this, it enters the completion rather than the desired keystroke. It strikes me as rare that someone would need the completion inside a comment, and wondered if it would help anyone else to simply not trigger completions inside comments?

### Repro steps

+ Open a .fsx file with a project and start entering a comment. 
+ Then place a space, or single character that would start a completion as the end of the line being entered. For instance ' ' or 'a'. This starts the completion menu from company mode.
+ Then hit enter.

### Expected behavior

Instead, the completion menu would never trigger because we're inside a comment block.

### Actual behavior

The completion menu triggers, suggests a completion, and that keyword is entered rather than a carriage return.

### Known workarounds

Cancelling company mode completion using C-g seems to work, just taxing to perpetually do on multi-line comments.

### Related information 

* Windows 10
* 25.1

**Comment by juergenhoetzel** [comment]
The current implementation changes the *global* `company-minimum-prefix-length` which results in all *company-backends* kicking off.

This only happens inside strings and comments because the fsharp-completion backends only passes control to other backends when `(point)` is outside strings and comments.

I openend pull request https://github.com/fsharp/emacs-fsharp-mode/pull/104

**Comment by rneatherway** [comment]
Fixed by #104

**Comment by nicholas-peterson** [comment]
Bah, I didn't see the dupe issue before mine :( . Thanks for fixing this!
