### ISSUE TITLE
Support for new .fsproj format

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsharp/emacs-fsharp-mode#129]
AFAIK, most of the work to load the new .fsproj format is done by FSAC so supporting it in emacs should be quite straight forward (apparently it's not the case at the moment), or am I missing something?

Ping @enricosada, @krgn

**Comment by krgn** [comment]
Yeah, I'm having this problem loading the project file with this error:

```
1493239639.5755842: project "/path/to/fable/Frontend/Frontend.fsproj" verbose 
1493239640.2211804: {"Kind":"error","Data":"Could not find a part of the path \"/path/to/fable/Frontend/obj/Frontend.fsproj.proj-info.targets\"."}
```
That file indeed does not exist, and the project builds fine otherwise. Any ideas why this might be happening?

Thx!

**Comment by enricosada** [comment]
@krgn have you done `dotnet restore` before? it's a prerequisite atm.

After restore an `obj` directory is created with a `obj/project.assets.json`. after that should work.
Probably now is failing because that dir doesnt exists

so

```
dotnet new console -lang f#
dotnet restore
dotnet build
```

if all works, now FSAC should parse correctly (as i said, just `dotnet restore` is required)

I already added an issue ( https://github.com/enricosada/dotnet-proj-info/issues/3 ) to improve error message if not restored

**Comment by krgn** [comment]
Ah yes that did the trick, thank you! As an explanation: I didn't call `dotnet restore` on the specific sub-project, but only the top-level `.proj` file.

**Comment by enricosada** [comment]
If A reference B (with a `ProjectReference`), and you `dotnet restore` A, then B should be automatically restored too.
do you have a repro? just fsproj is ok

**Comment by alfonsogarciacaro** [comment]
So it was already working! Sorry, my bad 😅  The `.proj` file on the root folder is just there to download the dotnet-fable CLI tool.

Thanks a lot for your help, @enricosada!

**Comment by enricosada** [comment]
np, @alfonsogarciacaro i really need to improve the error message if is not restored :sweat_smile:
