### ISSUE TITLE
Clean install on emacs 24.5 on windows crash when opening *.fs file

### ISSUE THREAD

**Issue by Andrea** [fsharp/emacs-fsharp-mode#39]
Hi there

Disclaimer : I am pretty new to using Emacs

This is vanilla Emacs 24.5.1 just installed downloaded with a pretty empty init.el. And fsharp-mode just installed from Melpa 
As soon as I open a *.fs file I get a crash saying 

```

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

   at FsAutoComplete.Main.entry(String[] args)
```
I set up the paths to fsc.exe and fsi.exe as per instructions 

This happens both in Vanilla Emacs and Spacemacs

Thanks for any tips :D

**Comment by rneatherway** [comment]
Hi, I'm sorry but I made a mistake with the last release. I've just pushed an updated version, which MELPA will take a few hours to pick up. Please try again when it is on MELPA and let me know if it fixes your issue.

**Comment by Andrea** [comment]
Thanks a mill, testing it now :D (will close if it works)

**Comment by Andrea** [comment]
Ok, not crashing anymore :) Thanks

However I can't get intellisense , in messages

```
Error: background intellisense process not running.
```
will see if I can get more info

**Comment by rneatherway** [comment]
Ah, sorry to hear that! It turns out the packaging recipe wasn't including the application configuration file. I've submitted a pull request at https://github.com/milkypostman/melpa/pull/3304 so hopefully it will be merged soon. In the meantime, if you want to get things going you could drop the file `fsautocomplete.exe.config` from http://github.com/rneatherway/emacs-fsharp-mode-bin into your `~/.emacs.d/elpa/fsharp-mode-20151115/bin` folder.

**Comment by rneatherway** [comment]
Right, the new version should fix this if you uninstall and reinstall the package.

**Comment by Andrea** [comment]
Finally got time to test it, looking great, thanks a million :D
